name: flutter_doguber_frontend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  geocoding: ^3.0.0
  geolocator: ^12.0.0
  go_router: ^13.2.2
  google_maps_flutter: ^2.2.8
  http: ^1.2.1
  http_parser: ^4.0.2
  image_picker: ^1.1.1
  kakao_flutter_sdk: ^1.9.1+2
  localstorage: ^5.0.0
  provider: ^6.1.2
  stomp_dart_client: ^2.0.0
  webview_flutter: ^4.7.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/